### ISSUE TITLE
Secret Benchmarking checkup

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#16]
Nionis has finished the code for secret benchmarking, could someone take a look and see if they're able to run it locally, can follow the instructions easily, or notice any other issues? 

https://github.com/nionis/enigma-benchmarking

**Comment by levackt** [comment]
After npm install, discovery fails to compile with the below error.
Checking if it's my version, just upgraded yesterday.

➜  enigma-benchmarking git:(master) ✗ discovery compile
Cannot find the expected directory structure.
➜  enigma-benchmarking git:(master) ✗ discovery --version
0.1.0


**Edit: fixed by creating the missing build dir**

**Comment by levackt** [comment]
Fails to start due to env vars not set, so something to add to the readme or provide some default env;

➜  enigma-benchmarking git:(master) ✗ discovery start
Starting Enigma Network...
The DOCKER_TAG variable is not set. Defaulting to a blank string.
The BUILD_CONTRACTS_PATH variable is not set. Defaulting to a blank string.
The COMPOSE_PROJECT_NAME variable is not set. Defaulting to a blank string.
Creating network "enigma-benchmarking_net" with the default driver
Creating volume "enigma-benchmarking_shared" with default driver
no such image: enigmampc/enigma_contract:: invalid reference format
(node:42984) UnhandledPromiseRejectionWarning: Error: child exited with code 1

**Comment by levackt** [comment]
With the .env fixed, discovery starts.

With the client also started I can test the application.
Error handling can be improved to inform the user, eg when trying to submit a tx with 
an account that doesn’t have ENG we get **name: "NotEnoughTokens", message: "Not enough tokens to pay the fee"**.
Currently it just says "Something went bad, please retry".

**Comment by levackt** [comment]
https://github.com/nionis/enigma-benchmarking/blob/master/client/src/env.ts#L4

This can be localhost ("http://localhost:3346") since the port is mapped.
Then there's no need to edit client/src/env.ts

**Comment by levackt** [comment]
discovery test works but I haven't been able to upload a file yet, fails with the following error in enigma, while the client hangs and doesn't display any error.

> p2p_1       | [Sat Sep 28 2019 04:08:52 GMT+0000 (Coordinated Universal Time)] DEBUG [VERIFY_NEW_TASK] successful verification of task eebc2fa94431bd83d354ad3cab16435dc8e25fec9b3440a74564d259e347f28c
p2p_1       | [Sat Sep 28 2019 04:08:52 GMT+0000 (Coordinated Universal Time)] DEBUG [onVerifyTask] saved to db task eebc2fa94431bd83d354ad3cab16435dc8e25fec9b3440a74564d259e347f28c
core_1      | 04:08:52 [INFO] compute_task() => Err(DBErr { command: "read", kind: MissingKey }
core_1      |
core_1      | stack backtrace:
core_1      |    0: failure::backtrace::internal::InternalBacktrace::new::h87f5fbf63375cb0b (0x55a46ba8c873)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
core_1      |    1: failure::backtrace::Backtrace::new::ha287589ac84712e1 (0x55a46ba8c61e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
core_1      |    2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h37c34fdfb085f89c (0x55a46af4268a)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
core_1      |    3: <failure::error::Error as core::convert::From<F>>::from::hd2ad898ca25dc7ed (0x55a46af06de2)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
core_1      |    4: <enigma_core_app::db::dal::DB as enigma_core_app::db::dal::CRUDInterface<failure::error::Error,&K,alloc::vec::Vec<u8>,&[u8]>>::read::{{closure}}::{{closure}}::h8e834bf83080c54a (0x55a46afb6205)
core_1      |              at src/db/dal.rs:184
core_1      |    5: <enigma_core_app::db::primitives::DeltaKey as enigma_core_app::db::primitives::SplitKey>::as_split::he82e58407fb7308f (0x55a46af5ec5b)
core_1      |              at src/db/primitives.rs:76
core_1      |    6: <enigma_core_app::db::dal::DB as enigma_core_app::db::dal::CRUDInterface<failure::error::Error,&K,alloc::vec::Vec<u8>,&[u8]>>::read::{{closure}}::he2341d970ed4b429 (0x55a46afb6921)
core_1      |              at src/db/dal.rs:182
core_1      |    7: <enigma_core_app::db::dal::DB as enigma_core_app::db::dal::CRUDInterface<failure::error::Error,&K,alloc::vec::Vec<u8>,&[u8]>>::read::h0f51351caeb133b9 (0x55a46afb5e33)
core_1      |              at src/db/dal.rs:180
core_1      |    8: <enigma_core_app::db::dal::DB as enigma_core_app::db::iterator::P2PCalls<alloc::vec::Vec<u8>>>::get_contract::{{closure}}::h58adfdf04700c007 (0x55a46af3c51b)
core_1      |              at src/db/iterator.rs:333
core_1      |    9: <enigma_core_app::db::dal::DB as enigma_core_app::db::iterator::P2PCalls<alloc::vec::Vec<u8>>>::get_contract::ha1b61fde0a8b946e (0x55a46af3eab1)
core_1      |              at src/db/iterator.rs:330
core_1      |   10: enigma_core_app::networking::ipc_listener::handling::compute_task::{{closure}}::h7fe00d96c816787b (0x55a46af29b23)
core_1      |              at src/networking/ipc_listener.rs:369
core_1      |   11: enigma_core_app::networking::ipc_listener::handling::compute_task::h971979db47ef91a3 (0x55a46afc341c)
core_1      |              at src/networking/ipc_listener.rs:361
core_1      |   12: enigma_core_app::networking::ipc_listener::handle_message::h620847a335fd122c (0x55a46af0f466)
core_1      |              at src/networking/ipc_listener.rs:50
core_1      |   13: enigma_core_app::main::{{closure}}::h4a61852353f9e40f (0x55a46aee98f9)
core_1      |              at src/main.rs:35
core_1      |   14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h3f8f6a338cd3bf5d (0x55a46aee97ab)
core_1      |              at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/ops/function.rs:279
core_1      |   15: core::option::Option<T>::map::h99dacff9401235c5 (0x55a46aede6cf)
core_1      |              at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/option.rs:416
core_1      |   16: <futures::stream::map::Map<S,F> as futures::stream::Stream>::poll::h179740fc7105dffa (0x55a46aee9451)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/stream/map.rs:79
core_1      |   17: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll::h72e8c529aed8b656 (0x55a46aeda53b)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/stream/forward.rs:94
core_1      |   18: <futures::future::map::Map<A,F> as futures::future::Future>::poll::h55f33a2e617ca0b7 (0x55a46aee4a9e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/map.rs:30
core_1      |   19: futures::future::chain::Chain<A,B,C>::poll::hcc4a0ee0cf8e87be (0x55a46aee696c)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/chain.rs:32
core_1      |   20: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::haa95fdbef1c31e98 (0x55a46aef9c6a)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/and_then.rs:32
core_1      |   21: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::hc251a56c38b12f21 (0x55a46aef739a)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:329
core_1      |   22: futures::task_impl::Spawn<T>::enter::{{closure}}::hb15ab10e28ecb22a (0x55a46aef7517)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:399
core_1      |   23: futures::task_impl::std::set::h4ae952ed1d8c5c12 (0x55a46aefbc61)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:83
core_1      |   24: futures::task_impl::Spawn<T>::enter::h81914a4c278f70fc (0x55a46aef74a3)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:399
core_1      |   25: futures::task_impl::Spawn<T>::poll_fn_notify::he45d382ceb6769fa (0x55a46aef72c5)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:291
core_1      |   26: futures::task_impl::Spawn<T>::poll_future_notify::hc8c0c744dd97d258 (0x55a46aef736e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:329
core_1      |   27: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::{{closure}}::h57718c28b2b70b21 (0x55a46aefbd59)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:236
core_1      |   28: futures::task_impl::std::ThreadNotify::with_current::{{closure}}::h1d6eb8ba19239bc8 (0x55a46aefbb7f)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:483
core_1      |   29: std::thread::local::LocalKey<T>::try_with::hde3a75c2c7ba09a7 (0x55a46aee5c74)
core_1      |              at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/thread/local.rs:299
core_1      |   30: std::thread::local::LocalKey<T>::with::h01be2a158648d744 (0x55a46aee5a71)
core_1      |              at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/thread/local.rs:245
core_1      |   31: futures::task_impl::std::ThreadNotify::with_current::h9e0cd9106acf3cae (0x55a46aefbb3e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:483
core_1      |   32: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::hf52cf103f94ba993 (0x55a46aef7544)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:233
core_1      |   33: futures::future::Future::wait::h96f40c6b030e892f (0x55a46aef9b70)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/mod.rs:299
core_1      |   34: enigma_core_app::main::he17802e79deb4755 (0x55a46aef7022)
core_1      |              at src/main.rs:34
core_1      |   35: std::rt::lang_start::{{closure}}::h4ae16111a825ad8d (0x55a46aef8be0)
core_1      |              at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
core_1      |   36: {{closure}} (0x55a46beeee33)
core_1      |              at src/libstd/rt.rs:49
core_1      |       do_call<closure,i32>
core_1      |              at src/libstd/panicking.rs:293
core_1      |   37: __rust_maybe_catch_panic (0x55a46bef328a)
core_1      |              at src/libpanic_unwind/lib.rs:85
core_1      |   38: try<i32,closure> (0x55a46beef9fd)
core_1      |              at src/libstd/panicking.rs:272
core_1      |       catch_unwind<closure,i32>
core_1      |              at src/libstd/panic.rs:388
core_1      |       lang_start_internal
core_1      |              at src/libstd/rt.rs:48
core_1      |   39: std::rt::lang_start::hca02c93d86228e2c (0x55a46aef8bb9)
core_1      |              at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
core_1      |   40: main (0x55a46aef71ba)
core_1      |   41: __libc_start_main (0x7fe976ca5b97)
core_1      |   42: _start (0x55a46aed95fa)
core_1      |   43: <unknown> (0x0))
core_1      | 04:08:52 [ERROR] Unwrapped p2p Message failed: Error while trying to read, Because: The Key doesn't exist
p2p_1       | [Sat Sep 28 2019 04:08:53 GMT+0000 (Coordinated Universal Time)] ERROR response from Core{"id":"e8kKnYb4i0PM","type":"Error","msg":"Error while trying to read, Because: The Key doesn't exist"}

**Comment by lauracw100** [comment]
> 
> 
> https://github.com/nionis/enigma-benchmarking/blob/master/client/src/env.ts#L4
> 
> This can be localhost ("http://localhost:3346") since the port is mapped.
> Then there's no need to edit client/src/env.ts

I agree with @levackt on this one. It took me awhile to figure out what to put there and finally looked at the `test_benchmarking.js` code to see what value to use for `enigmaUrl`.

**Comment by lauracw100** [comment]
> 
> 
> Fails to start due to env vars not set, so something to add to the readme or provide some default env;
> 
> ➜ enigma-benchmarking git:(master) ✗ discovery start
> Starting Enigma Network...
> The DOCKER_TAG variable is not set. Defaulting to a blank string.
> The BUILD_CONTRACTS_PATH variable is not set. Defaulting to a blank string.
> The COMPOSE_PROJECT_NAME variable is not set. Defaulting to a blank string.
> Creating network "enigma-benchmarking_net" with the default driver
> Creating volume "enigma-benchmarking_shared" with default driver
> no such image: enigmampc/enigma_contract:: invalid reference format
> (node:42984) UnhandledPromiseRejectionWarning: Error: child exited with code 1

I agree @levackt on putting something in the README. I didn't have an issue with `discovery start`. I'm using the same version of `discovery-cli` as you.

**Comment by lauracw100** [comment]
> 
> 
> After npm install, discovery fails to compile with the below error.
> Checking if it's my version, just upgraded yesterday.
> 
> ➜ enigma-benchmarking git:(master) ✗ discovery compile
> Cannot find the expected directory structure.
> ➜ enigma-benchmarking git:(master) ✗ discovery --version
> 0.1.0
> 
> **Edit: fixed by creating the missing build dir**

Yeah, I got this error too.

I recommend he include an empty `build/` dir with a git keep file so other devs don't run into this issue.

**Comment by lauracw100** [comment]
I was able to upload a file after setting up my Metamask account using a local RPC network of `http://localhost:9545` and imported an account using the private key listed for `account[0]` found in the `discovery start` log.

NOTE: my feedback on the UI and UX don't indicate that there's an issue, but just trying to make it easier to understand and navigate for someone who uses it for the 1st time  without knowing what it's all about. My notes might be overkill for a bounty though ;-).

I'd like to see the UI improved so it's more clear what the user is expected to do. For example, there are these 3 headings and buttons on the main page:
1. Submit Your Quote
2. Fetch Tasks
3. Select Task

There's also a '+' button at the top right which takes you to the screen to add a dataset by uploading a file.

**UI Recommendations**:

_Home page_:
- add main heading similar to "Secret Benchmarking"
- pre-fetch the task names and remove the "Fetch Tasks" button
- _nice to have_: load at least 2 or 3 different task names so the dropdown has a few items to choose from
- make the tasks more task-like (e.g. instead of "server costs" use "Generic Security Audit")
- change the '+' button to be text indicating the operation (e.g. add task dataset)

_Percentile Task Results page_:
- change "Your quote is in the 99th percentile" to "Your quote is more expensive than 99% of other quotes"
- change "input: <rate>" to "rate: <rate>"

_Add Task Dataset page_:
- change "Upload Data" to "Add Task Dataset"
- change "Data Title" to "Task Name"
- change "Import a File" to "Import (json, csv)"
- when a dataset file is uploaded successfully, indicate it worked with a message
- handle error when invalid data is uploaded (see attached)
- maybe add a note to this page that says the dataset should have the task rates sorted in ascending order, otherwise you'll get incorrect results OR modify the code to sort the dataset when uploaded

**README Recommendations**:

- Include some screenshots and directions on how to use the UI
- add some notes about the Metamask operations required for each operation (upload vs submitting data for a quote). This was a bit confusing for me because I was asked to approve via MetaMask:
1. sign a message
2. approve a transaction
3. approve a contract interation
Eventually I figured out what I was supposed to do :-)
<img width="835" alt="Screen Shot 2019-09-28 at 5 43 09 PM" src="https://user-images.githubusercontent.com/436905/65823125-846ad180-e21e-11e9-9eb0-e15c97d63251.png">

**Comment by lacabra** [comment]
FYI, this is a known issue I need to address:
```
Cannot find the expected directory structure.
```

I'm now tracking it here: enigmampc/discovery-cli#19

**Comment by ainsleys** [comment]
Thanks for letting us know about that @lacabra , and thanks for the detailed feedback @levackt and @lauraweindorf !!

I've shared this feedback with Nionis! He'll let me know which of the reccs he can implement that are within scope and I'll close this issue when bounty is paid out :)

**Comment by nionis** [comment]
Hello guys, thank you for taking the time to give me feedback!

-------

> nice to have: load at least 2 or 3 different task names so the dropdown has a few items to choose from
> make the tasks more task-like (e.g. instead of "server costs" use "Generic Security Audit")

The project doesn't come with any default datasets, I believe the reason you saw this it's because you run the tests.
Normally, the enigma contract address you should use is the one you get after `discovery migrate`

-------

> maybe add a note to this page that says the dataset should have the task rates sorted in ascending order, otherwise you'll get incorrect results OR modify the code to sort the dataset when uploaded

I don't believe this should be an issue unless you have tested it, please let me know.

**Comment by nionis** [comment]
> add some notes about the Metamask operations required for each operation (upload vs submitting data for a quote). This was a bit confusing for me because I was asked to approve via MetaMask:
sign a message
approve a transaction
approve a contract interation

I want to add this on both projects, to be honest I am not sure how it works internally, for example why do you need to approve enigma tokens?
It would be very helpful to work together on this, perhaps you can make a PR with a short explanation on how it works.

**Comment by nionis** [comment]
latest master branch addresses these issues: https://github.com/nionis/enigma-benchmarking/issues/7

**Comment by levackt** [comment]
Thanks for the updates Steve, will dive back in later and check it out.

**Comment by nionis** [comment]
cool, updated the setup instructions too, make sure to check it out

**Comment by lauracw100** [comment]
> 
> 
> Hello guys, thank you for taking the time to give me feedback!
> 
> > nice to have: load at least 2 or 3 different task names so the dropdown has a few items to choose from
> > make the tasks more task-like (e.g. instead of "server costs" use "Generic Security Audit")
> 
> The project doesn't come with any default datasets, I believe the reason you saw this it's because you run the tests.
> Normally, the enigma contract address you should use is the one you get after `discovery migrate`
> 
> > maybe add a note to this page that says the dataset should have the task rates sorted in ascending order, otherwise you'll get incorrect results OR modify the code to sort the dataset when uploaded
> 
> I don't believe this should be an issue unless you have tested it, please let me know.

Hey Steve @nionis :-D. Yes, that must be it--that I ran the tests. I'll take another look at the latest too, in a day or two.

Disregard that comment about the task rates being sorted. I was following notes on how to calculate percentiles, but you're code handles it correctly!

**Comment by levackt** [comment]
> why do you need to approve enigma tokens?

@nionis 
When you create the task to save the addresses, you specify the ENG gas and gas limit, more in the [docs](https://enigma.co/discovery-documentation/API/#createtaskfn-args-gaslimit-gaspx-sender-scaddrorprecode-iscontractdeploymenttask-task)

Would suggest setting that a lot lower than 10 million in a real app :)

**Comment by nionis** [comment]
@levackt is there a way to figure what gas / gas limit is the best?

**Comment by levackt** [comment]
> @levackt is there a way to figure what gas / gas limit is the best?

Will get back to you on this one Steve

**Comment by levackt** [comment]
Choosing the lowest number (1) in the sample still results in "Your quote is more expensive than 40% of other quotes."

Not sure if this is just wording or the formula

**Comment by levackt** [comment]
Error handling was mentioned already, eg rate 0.99, the client hangs while the console logs "Error: invalid number value"

We can avoid submitting such payloads by validation or formatting, then if it passes we should inform the user of any errors from enigma.

**Comment by levackt** [comment]
> @levackt is there a way to figure what gas / gas limit is the best?

So the core logs the gas used by the task, eg;

> core_1      | 06:23:59 [INFO] compute_task() => Ok(ComputeTask { result: ComputeResult { used_gas: 925729, output: "30c236150ca6

Will look into whether this is gwei, wei or eth sort of units, and how to represent it as such.
For your example based on the above you can get away with 1000000.

Mind it varies depending on the computations, if there are different scenarios you'd set a limit based on worst case.

That said the upload size can vary a lot so 10m was as good a start as any.

Maybe we can detect this, or at least log it in tests with a plugin like eth-gas-reporter does.

**Comment by nionis** [comment]
> Choosing the lowest number (1) in the sample still results in "Your quote is more expensive than 40% of other quotes."
> 
> Not sure if this is just wording or the formula

I have changed the wording from "Your quote is in the 40th percentile" to "Your quote is more expensive than 40% of other quotes." according to the suggestions requested above, I believe the former is the proper language when it comes to percentiles, but to be honest I am not an expert in this so please correct me if I am wrong. I have switched it back to the former wording.

--------------

> Error handling was mentioned already, eg rate 0.99, the client hangs while the console logs "Error: invalid number value"
> 
> We can avoid submitting such payloads by validation or formatting, then if it passes we should inform the user of any errors from enigma.

I have improved the number input so it doesn't allow non integers, also improved uploading so it catches if the file contains non integers.

--------------

> > @levackt is there a way to figure what gas / gas limit is the best?
> 
> So the core logs the gas used by the task, eg;
> 
> > core_1      | 06:23:59 [INFO] compute_task() => Ok(ComputeTask { result: ComputeResult { used_gas: 925729, output: "30c236150ca6
> 
> Will look into whether this is gwei, wei or eth sort of units, and how to represent it as such.
> For your example based on the above you can get away with 1000000.
> 
> Mind it varies depending on the computations, if there are different scenarios you'd set a limit based on worst case.
> 
> That said the upload size can vary a lot so 10m was as good a start as any.
> 
> Maybe we can detect this, or at least log it in tests with a plugin like eth-gas-reporter does.

I am gonna leave this up to you guys until we have a solid way to determine these details.
[Here](https://github.com/nionis/enigma-benchmarking/blob/master/client/src/models/EnigmaTransaction.ts#L19) is the place where this is handled.

**Comment by ainsleys** [comment]
Hey @nionis -- it would be great if you can make a screen recording of using this app too. I'll go ahead and release the bounty on this.

**Comment by ainsleys** [comment]
@lauraweindorf / @levackt -- if either of you have a few minutes to take some screenshots of the application, it would really help jazz it up for the readme. I'm hoping to get this ready as an educational resource for our upcoming hackathon. For now, I'm just going to make every bounty it's own repo. We can optimize this in the future :). See https://github.com/enigmampc/enigma-benchmarking

cc @nionis -- let's make any further pull requests for the app on this enigma-owned repo going forward

**Comment by levackt** [comment]
> @lauraweindorf / @levackt -- if either of you have a few minutes to take some screenshots of the application, it would really help jazz it up for the readme. I'm hoping to get this ready as an educational resource for our upcoming hackathon. 

Sure, on it

> For now, I'm just going to make every bounty it's own repo. We can optimize this in the future :)

+1

**Comment by levackt** [comment]
![Screenshot 2019-10-17 at 09 06 10](https://user-images.githubusercontent.com/10286403/66985670-91f8d600-f0bd-11e9-8735-65052db827e5.png)
![Screenshot 2019-10-17 at 09 05 37](https://user-images.githubusercontent.com/10286403/66985671-92916c80-f0bd-11e9-8eb7-99d762d8618a.png)
![Screenshot 2019-10-17 at 09 05 24](https://user-images.githubusercontent.com/10286403/66985672-92916c80-f0bd-11e9-9ca9-f96c9e6ed764.png)
![Screenshot 2019-10-17 at 09 05 11](https://user-images.githubusercontent.com/10286403/66985673-932a0300-f0bd-11e9-9cea-b370773efd54.png)
![Screenshot 2019-10-17 at 09 02 36](https://user-images.githubusercontent.com/10286403/66985674-932a0300-f0bd-11e9-8e21-b67d14ef08b0.png)
![Screenshot 2019-10-17 at 09 02 04](https://user-images.githubusercontent.com/10286403/66985675-93c29980-f0bd-11e9-8527-1c7883b680e8.png)
![Screenshot 2019-10-17 at 09 01 48](https://user-images.githubusercontent.com/10286403/66985676-93c29980-f0bd-11e9-80f9-cd25644dc311.png)
![Screenshot 2019-10-17 at 09 01 32](https://user-images.githubusercontent.com/10286403/66985677-93c29980-f0bd-11e9-906a-951baa8f724e.png)
![Screenshot 2019-10-17 at 09 01 17](https://user-images.githubusercontent.com/10286403/66985678-945b3000-f0bd-11e9-932a-6d98597aa701.png)
![Screenshot 2019-10-17 at 09 00 12](https://user-images.githubusercontent.com/10286403/66985680-945b3000-f0bd-11e9-80d3-b0f79875df85.png)
![Screenshot 2019-10-17 at 08 59 35](https://user-images.githubusercontent.com/10286403/66985681-945b3000-f0bd-11e9-82b9-0a0c8de03933.png)


Github renamed the files but preserved the time in the link text, start from the bottom.

**Comment by lauracw100** [comment]
Nice snaphsots @levackt! 

@ainsleys should we close this issue? I was thinking of adding an issue to the project that was forked, now under the enigmampc repo, to update the README with a description of how to use the DApp and include some or all of these screen shots.

The other bounties don't have screenshots illustrating the flow in the app though so maybe they're not needed for the READMEs. 

What are your thoughts?

**Comment by lauracw100** [comment]
Oops I just read what you wrote above @ainsleys :-).

**Comment by ainsleys** [comment]
Hi @lauraweindorf  -- closing this issue now! We may revisit the bounties in the future to standardize or update them but will be part of a separate effort
