### ISSUE TITLE
NFT Lottery (bounty checkup)

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#18]
One more bounty to run and check to see if--
- readme/docs are clear
- ui makes sense
- app runs as expected!

https://github.com/nionis/enigma-non-fungable-token-lottery

**Comment by levackt** [comment]
Installation:
<s>
Missing build dir
No .env or example .env
Set enigma url to localhost
</s>
With the above fixed, the readme is sufficient for installation. 
The tests pass and discovery starts and migrates.

There are no docs for usage or what problem the application solves, a readme in the client would be helpful.

Usage:
Would be helpful to provide a sample of the 100 whitelisted address.
<s>
Took a few tries to submit my 100 addresses, same data after resetting account multiple times.
I first got an RPC error signing and approving;

Uncaught (in promise) Error: Internal JSON-RPC error.
{
  "originalError": {}
}
    at Object._fireError (index.js:56)
    at sendTxCallback (index.js:491)
    at index.js:136
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)


Then I got the same benchmarking error, missing key;

p2p_1       | [Fri Oct 04 2019 04:16:21 GMT+0000 (Coordinated Universal Time)] DEBUG [VERIFY_NEW_TASK] successful verification of task 88987af7d35eabcad95915b93bfd3d2bc3308f06b7197478b0dfca268f0497dc
p2p_1       | [Fri Oct 04 2019 04:16:21 GMT+0000 (Coordinated Universal Time)] DEBUG [onVerifyTask] saved to db task 88987af7d35eabcad95915b93bfd3d2bc3308f06b7197478b0dfca268f0497dc
core_1      | 04:16:21 [INFO] compute_task() => Err(DBErr { command: "read", kind: MissingKey }
core_1      |
core_1      | stack backtrace:
core_1      |    0: failure::backtrace::internal::InternalBacktrace::new::h87f5fbf63375cb0b (0x564d4582e873)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
core_1      |    1: failure::backtrace::Backtrace::new::ha287589ac84712e1 (0x564d4582e61e)


Will dig a bit and make sure my env is not the cause, since the benchmark project worked for Laura.
</s>

**Comment by levackt** [comment]
In terms of being feature complete, the tests cover the roll function but don't check if there's a winner and if the lottery is COMPLETE

Looking at the contract code there's a max participants of 1000, which should be 100 for whitelisted, and then 10 participants before choosing a winner.

**Comment by lauracw100** [comment]
> Installation:
> 
> Missing build dir
> No .env or example .env
> Set enigma url to localhost
> 
> With the above fixed, the readme is sufficient for installation.
> The tests pass and discovery starts and migrates.
> 
> There are no docs for usage or what problem the application solves, a readme in the client would be helpful.

I have the same comments here as @levackt. 

**My Recommendations**:

1. The README should explicitly state that the enigma contract address (secret contract) address needs to be set to the lottery secret contract's deployed address, which can be found under the test/lottery.txt file. I would even include a code snippet of what that would look like. Nothing like visuals!

2. Also, above that kind of info should be an item telling the user/dev to run `discovery test`. There's something about seeing the tests run and pass that makes you feel warm and fuzzy. Plus, reviewing the test JS is a good way to see how to interact with the secret contract without the complexity of the react dapp in the mix at that point.

3. I would really like to see a summary of the bounty and, as @levackt mentioned, information on what's being solved--what it's all about. That makes it much more exciting for someone to want to dig into it, fork it, etc.

4. Either a readme in the client area or as part of the main README it would be great to see a walk-through and screenshots of the dapp explaining the flow and what's happening.

**UI Recommendations**:

I really had no idea what I was supposed to do as a user when I launched the dapp. The only thing I saw was mention of "NFT," a button saying I "Lost" with a sad face, a "1" with what looks like a broken image and a '+' button at the top right. 

<img width="1054" alt="Screen Shot 2019-10-05 at 1 48 46 PM" src="https://user-images.githubusercontent.com/436905/66259862-cc40aa00-e784-11e9-841d-def264ec24a9.png">

1. (opt) Change title from "Encrypted NFT lotteries ..." to "Encrypted Non-Fungible Token (NFT) Lottery".

2. Change '+' button to "Add Lottery" or similar

3. On the Add Lottery screen, I'm not sure why there's a "Skip" button? It doesn't seem like those steps should be allowed to be skipped. 

4. Could we change the "Go" button to "Next" to indicate to the user they're moving through a process of submitting information/tokens?

5. On the step 1 where you have to submit the 100 whitelisted addresses it would be nice to have verbiage that makes it clearer what you're trying to do, such as:
"Add Addresses for Lottery Participation (up to 100)" or similar

Underneath there's verbiage that says "(every new line in an address)". Maybe just reword that to be: "(one address per line)".

Also, it would be great if the list was pre-populated with at least 10 addresses from the ganache-cli accounts.

6. Add a note to the README about what the Metamask interaction is to help the user/dev understand what's going on (message signing, approve pmt, approve contract interaction).

7. On step 2 it's a bit unclear on how/where to obtain an NFT address. I realized later that the bounty actually has an NFT token as one of the smart contracts and is deployed during migration. I'm wondering if step 2 could just display the NFT contract address and let the user just enter the token ID. The instruction could be "Mint NFT Token" instead of "Approve token so it can be deposited." 

<img width="522" alt="Screen Shot 2019-10-05 at 3 48 21 PM" src="https://user-images.githubusercontent.com/436905/66260072-c8faed80-e787-11e9-87ae-9d7c4730a742.png">

I'm not sure why this part can be skipped either because I thought it was required for the flow/implementation of the secret lottery to work properly?

8. Shouldn't the default max participants be set to 5 per the Bounty requirements? It's set to 2 max participants in the dapp.

9. I tested with an account that had 0 ETH and got an error with the text of: "[object Object]". I would make that more obvious that it's an error and show an error message.
Opening the dev tools I see the error message is: 
```
message: "Not enough tokens to pay the fee"
name: "NotEnoughTokens"
```
10. I then used an account with plenty of ETH and entered an NFT token address I previously created and deployed on Rinkeby and got a message: "Error: failed" with this in the dev tools console:

<img width="420" alt="Screen Shot 2019-10-05 at 4 25 03 PM" src="https://user-images.githubusercontent.com/436905/66260443-b6cf7e00-e78c-11e9-960e-e22b109513a0.png">

If possible, make the error message more meaningful?

11. Add some text to the README to record the address of the NFT contract during migration, which is what should be entered into the UI.

12. When I used the NFT address to create the lottery, I got an error. Not sure why.

<img width="1011" alt="Screen Shot 2019-10-05 at 4 43 13 PM" src="https://user-images.githubusercontent.com/436905/66260685-eb910480-e78f-11e9-85d9-aef7e8ef2acc.png">
<img width="1086" alt="Screen Shot 2019-10-05 at 4 43 33 PM" src="https://user-images.githubusercontent.com/436905/66260689-f350a900-e78f-11e9-8221-cf9a24d7c9ec.png">

13. If there's an error creating the lottery and you close the page by clicking on the 'X' and then try clicking the '+' to create a fresh new lottery, you go back to where you were when the error occurred with no way to create a new lottery.

I'm still trying to get the "create a lottery" function to work .... will try some more tomorrow to figure out what the issue is.

**Comment by levackt** [comment]
Rebuilt node after updating and managed to get my txs confirmed. 
+1 all the above, the UX and error messages could use some love.

Not sure about your error but why are you using Rinkeby?

**Comment by levackt** [comment]
<s>
I'd expect some docs about the NFT steps outside the dapp too, eg jump into truffle console, create an instance of the token, mint it for your user, note the contract address. 

To simplify the NFT minting, a truffle post deployment script to mint for the 1st account (owner) should work nicely.

https://www.trufflesuite.com/docs/truffle/getting-started/writing-external-scripts
</s>

Fixed by providing deploy scripts

**Comment by lauracw100** [comment]
> 
> 
> Rebuilt node after updating and managed to get my txs confirmed.
> +1 all the above, the UX and error messages could use some love.
> 
> Not sure about your error but why are you using Rinkeby?

Good point! I was just playing around with data for the UI. Not sure what I was thinking ;-).

**Comment by nionis** [comment]
> Missing build dir
No .env or example .env
Set enigma url to localhost

fixed these on the latest master

**Comment by levackt** [comment]
I've signed and submitted all txs until step 3, everything seems to be ok but the front end throws an error here;
https://github.com/nionis/enigma-non-fungable-token-lottery/blob/master/client/src/models/EnigmaTransaction.ts#L80

What's the reason for this error? Code comments can be helpful to the dev, as well as a more descriptive error message, currently it says "Failed" so the user wouldn't know whether to wait or retry.

**Comment by nionis** [comment]
@levackt did you have this issue before yesterdays update?

**Comment by levackt** [comment]
> @levackt did you have this issue before yesterdays update?

No, but I can reproduce it repeatedly now and I don't see anything suspicious to revert and test.
If it doesn't happen when whitelisting addresses, it happens on the final step creating the lottery, in the former the task status is 3 and the latter it's 4, from a few tests anyway.
Still no errors or warnings in the discovery console.

**Comment by nionis** [comment]
@levackt The only instance where I was able to recreate the error is when I don't reset metamask after discovery start, more info [here](https://github.com/nionis/enigma-non-fungable-token-lottery#pitfalls).
Other than that the most common issue I have is the [epoch](https://github.com/enigmampc/dev-help/issues/8) issue.

**Comment by nionis** [comment]
On [this commit](https://github.com/nionis/enigma-non-fungable-token-lottery/commit/e3477916baedc634d20f9d0b6e04ebf4cca63285) I have added a few handy scripts to help you guys create erc721 contract and mint tokens.

**Comment by levackt** [comment]
> On [this commit](https://github.com/nionis/enigma-non-fungable-token-lottery/commit/e3477916baedc634d20f9d0b6e04ebf4cca63285) I have added a few handy scripts to help you guys create erc721 contract and mint tokens.

Thanks Steve.
I think if you include extra scripts you should also add them to the docs for usage, and/or include in  package.json so it's part of the build.
You can also have post deploy scripts, but I just included the minting if in development env [like this ](https://github.com/levackt/enigma-non-fungable-token-lottery/commit/d2304edb793077203216dbcc16a3e4dd2958876e)

**Comment by levackt** [comment]
Can reproduce Laura's issue #9, though some scenarios result in the object and others result in "Error: failed" (when the account has already entered in the lottery for example or is not whitelisted)

Addressing those 2 categories should cover you for most error conditions in the app, errors from the server and browser.

**Comment by levackt** [comment]
When successfully entering the lottery, or "rolling" to end the lottery, you have to hard refresh to update the client state. Though the success criteria only includes failures it'd be nice to handle success too, stretch goal maybe :)

That said I finally got through the entire process, won and lost the lottery and have my NFT. Yay!
No idea why it took so many tries, I was resetting my account each run so it wasn't that in my case.

Will take a few more stabs in the next day or so with the debugger to try reproduce it again.

**Comment by nionis** [comment]
@levackt I also experience this. It seems to me sometimes the [epoch](https://github.com/enigmampc/dev-help/issues/8) issue occurs more than other times. I guess best way to confirm is to wait for the [epoch](https://github.com/enigmampc/dev-help/issues/8) fix.

**Comment by nionis** [comment]
> > On [this commit](https://github.com/nionis/enigma-non-fungable-token-lottery/commit/e3477916baedc634d20f9d0b6e04ebf4cca63285) I have added a few handy scripts to help you guys create erc721 contract and mint tokens.
> 
> Thanks Steve.
> I think if you include extra scripts you should also add them to the docs for usage, and/or include in package.json so it's part of the build.
> You can also have post deploy scripts, but I just included the minting if in development env [like this ](https://github.com/levackt/enigma-non-fungable-token-lottery/commit/d2304edb793077203216dbcc16a3e4dd2958876e)

Feel free to make PR's for any commits you have made on your fork, since I am not sure how this will be used it's hard for me to know what needs to be done in terms of presentation.
I have update the readme with how to use the scripts.

**Comment by nionis** [comment]
> Can reproduce Laura's issue #9, though some scenarios result in the object and others result in "Error: failed" (when the account has already entered in the lottery for example or is not whitelisted)
> 
> Addressing those 2 categories should cover you for most error conditions in the app, errors from the server and browser.

Since the users who entered the lottery are anonymous, we don't know when the account has already entered in the lottery. It will require 2 transactions which I believe it's not very user friendly.

**Comment by nionis** [comment]
> When successfully entering the lottery, or "rolling" to end the lottery, you have to hard refresh to update the client state. Though the success criteria only includes failures it'd be nice to handle success too, stretch goal maybe :)
> 
> That said I finally got through the entire process, won and lost the lottery and have my NFT. Yay!
> No idea why it took so many tries, I was resetting my account each run so it wasn't that in my case.
> 
> Will take a few more stabs in the next day or so with the debugger to try reproduce it again.

I have updated it so when the user creates the lottery, we refetch lotteries.

**Comment by levackt** [comment]
> > Can reproduce Laura's issue #9, though some scenarios result in the object and others result in "Error: failed" (when the account has already entered in the lottery for example or is not whitelisted)
> > Addressing those 2 categories should cover you for most error conditions in the app, errors from the server and browser.
> 
> Since the users who entered the lottery are anonymous, we don't know when the account has already entered in the lottery. It will require 2 transactions which I believe it's not very user friendly.

Sorry I wasn't clear, you don't need to check if the account entered the lottery, only handle the error when it's rejected.

The error message when using an account that doesn't have any ENG for example, can be fixed by displaying "err.message()" instead of err.toString() in the [catch](https://github.com/nionis/enigma-non-fungable-token-lottery/blob/master/client/src/models/EnigmaTransaction.ts#L98)

Mind this doesn't apply to all conditions handled here.

**Comment by lauracw100** [comment]
UDPATE: I thought I fixed this error, but it occurred after I joined the Lottery and the page wasn't updated and I had to refresh to see it change from `Participants 0/2` to `Participants 1/2`.

-----------

Hey @nionis, I was getting this error when running 'npm run dev' under the client and fixed it by running `npm i html-webpack-plugin@next`. Just an FYI in case you want to update the version of that plugin or make a note in your "Pitfalls" section of the README.

```
[ info ]  ready on http://localhost:3000
(node:95898) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at /Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/webpack-hot-middleware/middleware.js:111:38
    at /Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/webpack-hot-middleware/middleware.js:66:7
    at Array.forEach (<anonymous>)
    at everyClient (/Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/webpack-hot-middleware/middleware.js:65:26)
    at Object.publish (/Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/webpack-hot-middleware/middleware.js:110:7)
    at Function.middleware.publish (/Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/webpack-hot-middleware/middleware.js:48:17)
    at HotReloader.send.args [as send] (/Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/next/dist/server/hot-reloader.js:5:335)
    at /Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/next/dist/server/hot-reloader.js:15:391
    at typePromise.then.typeMessages (/Users/lauraweindorf/enigma/enigma-non-fungable-token-lottery/client/node_modules/next/dist/build/output/index.js:2:133)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:95898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by lauracw100** [comment]
In this latest version, the success page for creation of the Lottery, the UI steps are going off the screen for me, and the Homepage button has the text flowing out of the container. Is it possible to fix these? I'm not familiar with react so I'm not sure how much effort is involved there.

<img width="1664" alt="Screen Shot 2019-10-13 at 5 55 14 PM" src="https://user-images.githubusercontent.com/436905/66723084-faf0fd00-ede2-11e9-841e-8ff1b9a1bab5.png">

**Comment by levackt** [comment]
> In this latest version, the success page for creation of the Lottery, the UI steps are going off the screen for me, and the Homepage button has the text flowing out of the container. Is it possible to fix these? I'm not familiar with react so I'm not sure how much effort is involved there.
> 
> <img alt="Screen Shot 2019-10-13 at 5 55 14 PM" width="1664" src="https://user-images.githubusercontent.com/436905/66723084-faf0fd00-ede2-11e9-841e-8ff1b9a1bab5.png">

Made a [little PR](https://github.com/nionis/enigma-non-fungable-token-lottery/pull/1) for the button text.

**Comment by nionis** [comment]
update: I didn't realise the issue is in the terminal 👍 .
Yep I am aware of that issue, I haven't been able to find a solid fix for that, since it doesn't affect the client, I will wait until a proper fix is available.

---------

@lauraweindorf I am unable to recreate the "html-webpack-plugin@next" issue, could you delete client/node_modules folder, npm install and try again?
Also what node version are you using?

**Comment by nionis** [comment]
@lauraweindorf I am unable to recreate the "steps" issue :/

I do have the button issue tho

**Comment by levackt** [comment]
> update: I didn't realise the issue is in the terminal 👍 .
> Yep I am aware of that issue, I haven't been able to find a solid fix for that, since it doesn't affect the client, I will wait until a proper fix is available.
> 
> @lauraweindorf I am unable to recreate the "html-webpack-plugin@next" issue, could you delete client/node_modules folder, npm install and try again?
> Also what node version are you using?

Also tried Laura's fix and still got the error log, doesn't seem to break anything, as far as I can tell.
My node version is v11.15.0

**Comment by nionis** [comment]
following up https://github.com/enigmampc/dev-help/issues/18#issuecomment-538689101

(3) For example step 1 is only for contract owner, step 2 is there in case the token is already approved by the user.


(7) The secret contract can work with any NFT smart contract, so it's up to the user to enter his NFT token. The migration step shouldn't migrate a NFT smart contract in production.



(8) There can be up to 1000 participants in the lottery, I can set the default to 5.



(12) Probably epoch error.

**Comment by nionis** [comment]
latest version includes some UI improvements suggested at https://github.com/enigmampc/dev-help/issues/18#issuecomment-538689101

**Comment by ainsleys** [comment]
Thanks team! @nionis would you be able to create and share a short screencast video demonstrating the app? This will make it easy for me to share w/ the rest of our product team. It looks like aside from that we're pretty much all set. Do you want to make the PR for me to release the bounty?

**Comment by nionis** [comment]
@ainsleys Sure!
I have made a PR already over at gitcoin, feel free to release bounty.
Let me know if you need any changes.

**Comment by lauracw100** [comment]
> update: I didn't realise the issue is in the terminal 👍 .
> Yep I am aware of that issue, I haven't been able to find a solid fix for that, since it doesn't affect the client, I will wait until a proper fix is available.
> 
> @lauraweindorf I am unable to recreate the "html-webpack-plugin@next" issue, could you delete client/node_modules folder, npm install and try again?
> Also what node version are you using?

I'm using Node v10.16. 

> > update: I didn't realise the issue is in the terminal 👍 .
> > Yep I am aware of that issue, I haven't been able to find a solid fix for that, since it doesn't affect the client, I will wait until a proper fix is available.
> > @lauraweindorf I am unable to recreate the "html-webpack-plugin@next" issue, could you delete client/node_modules folder, npm install and try again?
> > Also what node version are you using?
> 
> Also tried Laura's fix and still got the error log, doesn't seem to break anything, as far as I can tell.
> My node version is v11.15.0

Yeah, it's not breaking anything for me either. My node version is 10.16 at this point, but I'll try upgrading and doing a clean `npm install.`

**Comment by lauracw100** [comment]
@nionis I got a couple of lotteries created and rolled. Yay!

The only issue I had was my 2nd user didn't have any ENG and I wasn't able to join the lottery until I transferred the 10,000,000 ENG tokens to that account.

Is it supposed to work that way? @levackt did you have to do that too?

I'm really thinking instructions are needed for the README. I can try to do some PRs when I get time later this week or next to make it clearer for devs who want to try it out.

**Comment by ainsleys** [comment]
@nionis cool! Let me know if you have time to make the screenflow? And I agree with @lauraweindorf -- if we can add more instructions to the README that would be great.

**Comment by levackt** [comment]
> @nionis I got a couple of lotteries created and rolled. Yay!
> 
> The only issue I had was my 2nd user didn't have any ENG and I wasn't able to join the lottery until I transferred the 10,000,000 ENG tokens to that account.
> 
> Is it supposed to work that way? @levackt did you have to do that too?
> 
> I'm really thinking instructions are needed for the README. I can try to do some PRs when I get time later this week or next to make it clearer for devs who want to try it out.

Yes you need ENG to participate in the lottery, not sure if you can do that without ENG but I'm still wanting to dive into ENG as gas. That said it'd be great to have some docs for both the dev and the user about these steps especially.

**Comment by ainsleys** [comment]
As with secret benchmarking, have moved this to its own Enigma repo. Would be awesome to either get a video or at least some screenshots of how to use the application. cc @lauraweindorf @levackt @nionis https://github.com/enigmampc/enigma-non-fungible-token-lottery

**Comment by nionis** [comment]
Do you guys think it is better to have a video or a slide show?

**Comment by ainsleys** [comment]
@nionis Either works! Whatever's easier for you. We can always make static images from a video, so video probably easier?

**Comment by ainsleys** [comment]
I am closing this issue as we've posted the bounties now. Further discussion can take place in our issue around documenting the bounties #19
