### ISSUE TITLE
Questions on internals of Enigma Protocol

### ISSUE THREAD

**Issue by lauracw100** [enigmampc/dev-help#24]
ARsakura is asking for some information on the internal implementation and concepts of the Enigma Protocol from these papers:

- [Decentralizing Privacy: Using Blockchain to ProtectPersonal Data](https://enigma.co/ZNP15.pdf)
- [Enigma: Decentralized Computation Platform withGuaranteed Privacy](https://s3.amazonaws.com/enigmaco-website/uploads/pdf/enigma_full.pdf)

cc: @ainsleys @lacabra 

Is there any discussion of these concepts under the Enigma documentation?

> I want to ask some questions about the paper ,
> 
> Decentralizing Privacy: Using Blockchain to Protect Personal Data
> 
> In this paper , it refer the Tdata , Taccess can store some information and send in blockchain.
> 
> I wonder the Tdata , Taccess , they both are transaction , but are they also smart contract?
> 
> Enigma: Decentralized Computation Platform with Guaranteed Privacy
> 
> In this paper , I wonder when share be generate? I know encrypted data & public data , but what cause share be generated?
> 
> data --(by policy encrypt)–> encrypted data --( what party in share? )
> 
> –> share --(for privacy)–> spdz (verified correct)
> 
> and , is share step equal the secret smart contract ? or spdz step.

**Comment by ainsleys** [comment]
We should just respond and tell this user that the white papers are not implementation specs for the current network, but outlined early possibilities for system design. The problem with answering these questions is that they refer to a multi-party compute architecture, and Discovery works with TEEs instead. I think we should refer this user to the current documentation... rather than try to answer these piece by piece.

**Comment by lauracw100** [comment]
Okay, great! I'll do that @ainsleys :-D.

**Comment by lauracw100** [comment]
Added Ainsley's response and pointed ARsakura to the Enigma documentation here: https://enigma.co/discovery-documentation

Forum post: https://forum.enigma.co/t/questions-of-the-paper/1114
