### ISSUE TITLE
"Wrong epoch for this task" error thrown

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/dev-help#8]
I believe @lacabra is familiar with what might be causing this issue

**Comment by lacabra** [comment]
This issue has already been resolved in our `develop` branches, but we haven't released that code into the `main` branch, and the `latest` docker images. Leaving this issue open until those changes are merged into the `latest` version.

**Comment by ainsleys** [comment]
Just checking to see if this still hasn't merged to `stable` version yet

**Comment by lacabra** [comment]
No, but I realized the following: if anyone is experiencing this issue, and wants to get ahead of the game, they can use the next branch that will eventually be merged into the stable `latest` by changing the following line in their `.env` configuration file to:
```
DOCKER_TAG=develop
```
Please note that this will require downloading an additional 16GB of docker images in addition to the ones the user may have already in their system tagged `latest`. 

They may want to run `docker images` and then `docker rmi IMAGE_ID` where `IMAGE_ID` is taken from the first command and delete these images from the system to save HD space.

This issue is to remain open until the merge takes place.

**Comment by lacabra** [comment]
The changes that addressed this issue were finally merged last week to the `master` branches of the main repos, and new docker images tagged `latest` were pushed out, and this can now be closed.
